/* automatically generated by rust-bindgen 0.72.1 */
use crate::{
    PFN_vkDestroyDevice, PFN_vkGetDeviceProcAddr, PFN_vkGetInstanceProcAddr, PFN_vkVoidFunction, VkAllocationCallbacks,
    VkDevice, VkDeviceCreateInfo, VkExtensionProperties, VkFlags, VkInstance, VkLayerProperties, VkPhysicalDevice,
    VkResult, VkStructureType,
};

#[repr(C)]
pub struct __BindgenUnionField<T>(::std::marker::PhantomData<T>);
impl<T> __BindgenUnionField<T> {
    #[inline]
    pub const fn new() -> Self {
        __BindgenUnionField(::std::marker::PhantomData)
    }
    #[inline]
    pub unsafe fn as_ref(&self) -> &T {
        unsafe { ::std::mem::transmute(self) }
    }
    #[inline]
    pub unsafe fn as_mut(&mut self) -> &mut T {
        unsafe { ::std::mem::transmute(self) }
    }
}
impl<T> ::std::default::Default for __BindgenUnionField<T> {
    #[inline]
    fn default() -> Self {
        Self::new()
    }
}
impl<T> ::std::clone::Clone for __BindgenUnionField<T> {
    #[inline]
    fn clone(&self) -> Self {
        *self
    }
}
impl<T> ::std::marker::Copy for __BindgenUnionField<T> {}
impl<T> ::std::fmt::Debug for __BindgenUnionField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__BindgenUnionField")
    }
}
impl<T> ::std::hash::Hash for __BindgenUnionField<T> {
    fn hash<H: ::std::hash::Hasher>(&self, _state: &mut H) {}
}
impl<T> ::std::cmp::PartialEq for __BindgenUnionField<T> {
    fn eq(&self, _other: &__BindgenUnionField<T>) -> bool {
        true
    }
}
impl<T> ::std::cmp::Eq for __BindgenUnionField<T> {}
pub const MAX_NUM_UNKNOWN_EXTS: u32 = 250;
pub const CURRENT_LOADER_LAYER_INTERFACE_VERSION: u32 = 2;
pub const MIN_SUPPORTED_LOADER_LAYER_INTERFACE_VERSION: u32 = 1;
pub const VK_CURRENT_CHAIN_VERSION: u32 = 1;
pub type PFN_GetPhysicalDeviceProcAddr =
    Option<unsafe extern "C" fn(instance: VkInstance, pName: *const ::std::os::raw::c_char) -> PFN_vkVoidFunction>;
pub const VkNegotiateLayerStructType_LAYER_NEGOTIATE_UNINTIALIZED: VkNegotiateLayerStructType = 0;
pub const VkNegotiateLayerStructType_LAYER_NEGOTIATE_INTERFACE_STRUCT: VkNegotiateLayerStructType = 1;
pub type VkNegotiateLayerStructType = ::std::os::raw::c_int;
#[repr(C)]
pub struct VkNegotiateLayerInterface {
    pub sType: VkNegotiateLayerStructType,
    pub pNext: *mut ::std::os::raw::c_void,
    pub loaderLayerInterfaceVersion: u32,
    pub pfnGetInstanceProcAddr: PFN_vkGetInstanceProcAddr,
    pub pfnGetDeviceProcAddr: PFN_vkGetDeviceProcAddr,
    pub pfnGetPhysicalDeviceProcAddr: PFN_GetPhysicalDeviceProcAddr,
}
/*
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkNegotiateLayerInterface"][::std::mem::size_of::<VkNegotiateLayerInterface>() - 48usize];
    ["Alignment of VkNegotiateLayerInterface"][::std::mem::align_of::<VkNegotiateLayerInterface>() - 8usize];
    ["Offset of field: VkNegotiateLayerInterface::sType"]
        [::std::mem::offset_of!(VkNegotiateLayerInterface, sType) - 0usize];
    ["Offset of field: VkNegotiateLayerInterface::pNext"]
        [::std::mem::offset_of!(VkNegotiateLayerInterface, pNext) - 8usize];
    ["Offset of field: VkNegotiateLayerInterface::loaderLayerInterfaceVersion"]
        [::std::mem::offset_of!(VkNegotiateLayerInterface, loaderLayerInterfaceVersion) - 16usize];
    ["Offset of field: VkNegotiateLayerInterface::pfnGetInstanceProcAddr"]
        [::std::mem::offset_of!(VkNegotiateLayerInterface, pfnGetInstanceProcAddr) - 24usize];
    ["Offset of field: VkNegotiateLayerInterface::pfnGetDeviceProcAddr"]
        [::std::mem::offset_of!(VkNegotiateLayerInterface, pfnGetDeviceProcAddr) - 32usize];
    ["Offset of field: VkNegotiateLayerInterface::pfnGetPhysicalDeviceProcAddr"]
        [::std::mem::offset_of!(VkNegotiateLayerInterface, pfnGetPhysicalDeviceProcAddr) - 40usize];
};*/

pub type PFN_vkNegotiateLoaderLayerInterfaceVersion =
    ::std::option::Option<unsafe extern "C" fn(pVersionStruct: *mut VkNegotiateLayerInterface) -> VkResult>;
pub type PFN_PhysDevExt = ::std::option::Option<unsafe extern "C" fn(phys_device: VkPhysicalDevice) -> VkResult>;
pub const VkLayerFunction__VK_LAYER_LINK_INFO: VkLayerFunction_ = 0;
pub const VkLayerFunction__VK_LOADER_DATA_CALLBACK: VkLayerFunction_ = 1;
pub const VkLayerFunction__VK_LOADER_LAYER_CREATE_DEVICE_CALLBACK: VkLayerFunction_ = 2;
pub const VkLayerFunction__VK_LOADER_FEATURES: VkLayerFunction_ = 3;
pub type VkLayerFunction_ = ::std::os::raw::c_int;

pub use self::VkLayerFunction_ as VkLayerFunction;
#[repr(C)]
pub struct VkLayerInstanceLink_ {
    pub pNext: *mut VkLayerInstanceLink_,
    pub pfnNextGetInstanceProcAddr: PFN_vkGetInstanceProcAddr,
    pub pfnNextGetPhysicalDeviceProcAddr: PFN_GetPhysicalDeviceProcAddr,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkLayerInstanceLink_"][::std::mem::size_of::<VkLayerInstanceLink_>() - 24usize];
    ["Alignment of VkLayerInstanceLink_"][::std::mem::align_of::<VkLayerInstanceLink_>() - 8usize];
    ["Offset of field: VkLayerInstanceLink_::pNext"][::std::mem::offset_of!(VkLayerInstanceLink_, pNext) - 0usize];
    ["Offset of field: VkLayerInstanceLink_::pfnNextGetInstanceProcAddr"]
        [::std::mem::offset_of!(VkLayerInstanceLink_, pfnNextGetInstanceProcAddr) - 8usize];
    ["Offset of field: VkLayerInstanceLink_::pfnNextGetPhysicalDeviceProcAddr"]
        [::std::mem::offset_of!(VkLayerInstanceLink_, pfnNextGetPhysicalDeviceProcAddr) - 16usize];
};
pub type VkLayerInstanceLink = VkLayerInstanceLink_;
#[repr(C)]
pub struct VkLayerDeviceInfo_ {
    pub device_info: *mut ::std::os::raw::c_void,
    pub pfnNextGetInstanceProcAddr: PFN_vkGetInstanceProcAddr,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkLayerDeviceInfo_"][::std::mem::size_of::<VkLayerDeviceInfo_>() - 16usize];
    ["Alignment of VkLayerDeviceInfo_"][::std::mem::align_of::<VkLayerDeviceInfo_>() - 8usize];
    ["Offset of field: VkLayerDeviceInfo_::device_info"]
        [::std::mem::offset_of!(VkLayerDeviceInfo_, device_info) - 0usize];
    ["Offset of field: VkLayerDeviceInfo_::pfnNextGetInstanceProcAddr"]
        [::std::mem::offset_of!(VkLayerDeviceInfo_, pfnNextGetInstanceProcAddr) - 8usize];
};
pub type VkLayerDeviceInfo = VkLayerDeviceInfo_;
pub type PFN_vkSetInstanceLoaderData =
    ::std::option::Option<unsafe extern "C" fn(instance: VkInstance, object: *mut ::std::os::raw::c_void) -> VkResult>;
pub type PFN_vkSetDeviceLoaderData =
    ::std::option::Option<unsafe extern "C" fn(device: VkDevice, object: *mut ::std::os::raw::c_void) -> VkResult>;
pub type PFN_vkLayerCreateDevice = ::std::option::Option<
    unsafe extern "C" fn(
        instance: VkInstance,
        physicalDevice: VkPhysicalDevice,
        pCreateInfo: *const VkDeviceCreateInfo,
        pAllocator: *const VkAllocationCallbacks,
        pDevice: *mut VkDevice,
        layerGIPA: PFN_vkGetInstanceProcAddr,
        nextGDPA: *mut PFN_vkGetDeviceProcAddr,
    ) -> VkResult,
>;
pub type PFN_vkLayerDestroyDevice = ::std::option::Option<
    unsafe extern "C" fn(
        physicalDevice: VkDevice,
        pAllocator: *const VkAllocationCallbacks,
        destroyFunction: PFN_vkDestroyDevice,
    ),
>;
pub const VkLoaderFeastureFlagBits_VK_LOADER_FEATURE_PHYSICAL_DEVICE_SORTING: VkLoaderFeastureFlagBits = 1;
pub type VkLoaderFeastureFlagBits = ::std::os::raw::c_int;
pub use self::VkLoaderFeastureFlagBits as VkLoaderFlagBits;
pub type VkLoaderFeatureFlags = VkFlags;
#[repr(C)]
pub struct VkLayerInstanceCreateInfo {
    pub sType: VkStructureType,
    pub pNext: *const ::std::os::raw::c_void,
    pub function: VkLayerFunction,
    pub u: VkLayerInstanceCreateInfo__bindgen_ty_1,
}
#[repr(C)]
pub struct VkLayerInstanceCreateInfo__bindgen_ty_1 {
    pub pLayerInfo: __BindgenUnionField<*mut VkLayerInstanceLink>,
    pub pfnSetInstanceLoaderData: __BindgenUnionField<PFN_vkSetInstanceLoaderData>,
    pub layerDevice: __BindgenUnionField<VkLayerInstanceCreateInfo__bindgen_ty_1__bindgen_ty_1>,
    pub loaderFeatures: __BindgenUnionField<VkLoaderFeatureFlags>,
    pub bindgen_union_field: [u64; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VkLayerInstanceCreateInfo__bindgen_ty_1__bindgen_ty_1 {
    pub pfnLayerCreateDevice: PFN_vkLayerCreateDevice,
    pub pfnLayerDestroyDevice: PFN_vkLayerDestroyDevice,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkLayerInstanceCreateInfo__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<VkLayerInstanceCreateInfo__bindgen_ty_1__bindgen_ty_1>() - 16usize];
    ["Alignment of VkLayerInstanceCreateInfo__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<VkLayerInstanceCreateInfo__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: VkLayerInstanceCreateInfo__bindgen_ty_1__bindgen_ty_1::pfnLayerCreateDevice"]
        [::std::mem::offset_of!(VkLayerInstanceCreateInfo__bindgen_ty_1__bindgen_ty_1, pfnLayerCreateDevice) - 0usize];
    ["Offset of field: VkLayerInstanceCreateInfo__bindgen_ty_1__bindgen_ty_1::pfnLayerDestroyDevice"]
        [::std::mem::offset_of!(VkLayerInstanceCreateInfo__bindgen_ty_1__bindgen_ty_1, pfnLayerDestroyDevice) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkLayerInstanceCreateInfo__bindgen_ty_1"]
        [::std::mem::size_of::<VkLayerInstanceCreateInfo__bindgen_ty_1>() - 16usize];
    ["Alignment of VkLayerInstanceCreateInfo__bindgen_ty_1"]
        [::std::mem::align_of::<VkLayerInstanceCreateInfo__bindgen_ty_1>() - 8usize];
    ["Offset of field: VkLayerInstanceCreateInfo__bindgen_ty_1::pLayerInfo"]
        [::std::mem::offset_of!(VkLayerInstanceCreateInfo__bindgen_ty_1, pLayerInfo) - 0usize];
    ["Offset of field: VkLayerInstanceCreateInfo__bindgen_ty_1::pfnSetInstanceLoaderData"]
        [::std::mem::offset_of!(VkLayerInstanceCreateInfo__bindgen_ty_1, pfnSetInstanceLoaderData) - 0usize];
    ["Offset of field: VkLayerInstanceCreateInfo__bindgen_ty_1::layerDevice"]
        [::std::mem::offset_of!(VkLayerInstanceCreateInfo__bindgen_ty_1, layerDevice) - 0usize];
    ["Offset of field: VkLayerInstanceCreateInfo__bindgen_ty_1::loaderFeatures"]
        [::std::mem::offset_of!(VkLayerInstanceCreateInfo__bindgen_ty_1, loaderFeatures) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkLayerInstanceCreateInfo"][::std::mem::size_of::<VkLayerInstanceCreateInfo>() - 40usize];
    ["Alignment of VkLayerInstanceCreateInfo"][::std::mem::align_of::<VkLayerInstanceCreateInfo>() - 8usize];
    ["Offset of field: VkLayerInstanceCreateInfo::sType"]
        [::std::mem::offset_of!(VkLayerInstanceCreateInfo, sType) - 0usize];
    ["Offset of field: VkLayerInstanceCreateInfo::pNext"]
        [::std::mem::offset_of!(VkLayerInstanceCreateInfo, pNext) - 8usize];
    ["Offset of field: VkLayerInstanceCreateInfo::function"]
        [::std::mem::offset_of!(VkLayerInstanceCreateInfo, function) - 16usize];
    ["Offset of field: VkLayerInstanceCreateInfo::u"][::std::mem::offset_of!(VkLayerInstanceCreateInfo, u) - 24usize];
};
#[repr(C)]
pub struct VkLayerDeviceLink_ {
    pub pNext: *mut VkLayerDeviceLink_,
    pub pfnNextGetInstanceProcAddr: PFN_vkGetInstanceProcAddr,
    pub pfnNextGetDeviceProcAddr: PFN_vkGetDeviceProcAddr,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkLayerDeviceLink_"][::std::mem::size_of::<VkLayerDeviceLink_>() - 24usize];
    ["Alignment of VkLayerDeviceLink_"][::std::mem::align_of::<VkLayerDeviceLink_>() - 8usize];
    ["Offset of field: VkLayerDeviceLink_::pNext"][::std::mem::offset_of!(VkLayerDeviceLink_, pNext) - 0usize];
    ["Offset of field: VkLayerDeviceLink_::pfnNextGetInstanceProcAddr"]
        [::std::mem::offset_of!(VkLayerDeviceLink_, pfnNextGetInstanceProcAddr) - 8usize];
    ["Offset of field: VkLayerDeviceLink_::pfnNextGetDeviceProcAddr"]
        [::std::mem::offset_of!(VkLayerDeviceLink_, pfnNextGetDeviceProcAddr) - 16usize];
};
pub type VkLayerDeviceLink = VkLayerDeviceLink_;
#[repr(C)]
pub struct VkLayerDeviceCreateInfo {
    pub sType: VkStructureType,
    pub pNext: *const ::std::os::raw::c_void,
    pub function: VkLayerFunction,
    pub u: VkLayerDeviceCreateInfo__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union VkLayerDeviceCreateInfo__bindgen_ty_1 {
    pub pLayerInfo: *mut VkLayerDeviceLink,
    pub pfnSetDeviceLoaderData: PFN_vkSetDeviceLoaderData,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkLayerDeviceCreateInfo__bindgen_ty_1"]
        [::std::mem::size_of::<VkLayerDeviceCreateInfo__bindgen_ty_1>() - 8usize];
    ["Alignment of VkLayerDeviceCreateInfo__bindgen_ty_1"]
        [::std::mem::align_of::<VkLayerDeviceCreateInfo__bindgen_ty_1>() - 8usize];
    ["Offset of field: VkLayerDeviceCreateInfo__bindgen_ty_1::pLayerInfo"]
        [::std::mem::offset_of!(VkLayerDeviceCreateInfo__bindgen_ty_1, pLayerInfo) - 0usize];
    ["Offset of field: VkLayerDeviceCreateInfo__bindgen_ty_1::pfnSetDeviceLoaderData"]
        [::std::mem::offset_of!(VkLayerDeviceCreateInfo__bindgen_ty_1, pfnSetDeviceLoaderData) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkLayerDeviceCreateInfo"][::std::mem::size_of::<VkLayerDeviceCreateInfo>() - 32usize];
    ["Alignment of VkLayerDeviceCreateInfo"][::std::mem::align_of::<VkLayerDeviceCreateInfo>() - 8usize];
    ["Offset of field: VkLayerDeviceCreateInfo::sType"]
        [::std::mem::offset_of!(VkLayerDeviceCreateInfo, sType) - 0usize];
    ["Offset of field: VkLayerDeviceCreateInfo::pNext"]
        [::std::mem::offset_of!(VkLayerDeviceCreateInfo, pNext) - 8usize];
    ["Offset of field: VkLayerDeviceCreateInfo::function"]
        [::std::mem::offset_of!(VkLayerDeviceCreateInfo, function) - 16usize];
    ["Offset of field: VkLayerDeviceCreateInfo::u"][::std::mem::offset_of!(VkLayerDeviceCreateInfo, u) - 24usize];
};
unsafe extern "C" {
    pub fn vkNegotiateLoaderLayerInterfaceVersion(pVersionStruct: *mut VkNegotiateLayerInterface) -> VkResult;
}
pub const VkChainType_VK_CHAIN_TYPE_UNKNOWN: VkChainType = 0;
pub const VkChainType_VK_CHAIN_TYPE_ENUMERATE_INSTANCE_EXTENSION_PROPERTIES: VkChainType = 1;
pub const VkChainType_VK_CHAIN_TYPE_ENUMERATE_INSTANCE_LAYER_PROPERTIES: VkChainType = 2;
pub const VkChainType_VK_CHAIN_TYPE_ENUMERATE_INSTANCE_VERSION: VkChainType = 3;
pub type VkChainType = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VkChainHeader {
    pub type_: VkChainType,
    pub version: u32,
    pub size: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkChainHeader"][::std::mem::size_of::<VkChainHeader>() - 12usize];
    ["Alignment of VkChainHeader"][::std::mem::align_of::<VkChainHeader>() - 4usize];
    ["Offset of field: VkChainHeader::type_"][::std::mem::offset_of!(VkChainHeader, type_) - 0usize];
    ["Offset of field: VkChainHeader::version"][::std::mem::offset_of!(VkChainHeader, version) - 4usize];
    ["Offset of field: VkChainHeader::size"][::std::mem::offset_of!(VkChainHeader, size) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VkEnumerateInstanceExtensionPropertiesChain {
    pub header: VkChainHeader,
    pub pfnNextLayer: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *const VkEnumerateInstanceExtensionPropertiesChain,
            arg2: *const ::std::os::raw::c_char,
            arg3: *mut u32,
            arg4: *mut VkExtensionProperties,
        ) -> VkResult,
    >,
    pub pNextLink: *const VkEnumerateInstanceExtensionPropertiesChain,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkEnumerateInstanceExtensionPropertiesChain"]
        [::std::mem::size_of::<VkEnumerateInstanceExtensionPropertiesChain>() - 32usize];
    ["Alignment of VkEnumerateInstanceExtensionPropertiesChain"]
        [::std::mem::align_of::<VkEnumerateInstanceExtensionPropertiesChain>() - 8usize];
    ["Offset of field: VkEnumerateInstanceExtensionPropertiesChain::header"]
        [::std::mem::offset_of!(VkEnumerateInstanceExtensionPropertiesChain, header) - 0usize];
    ["Offset of field: VkEnumerateInstanceExtensionPropertiesChain::pfnNextLayer"]
        [::std::mem::offset_of!(VkEnumerateInstanceExtensionPropertiesChain, pfnNextLayer) - 16usize];
    ["Offset of field: VkEnumerateInstanceExtensionPropertiesChain::pNextLink"]
        [::std::mem::offset_of!(VkEnumerateInstanceExtensionPropertiesChain, pNextLink) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VkEnumerateInstanceLayerPropertiesChain {
    pub header: VkChainHeader,
    pub pfnNextLayer: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *const VkEnumerateInstanceLayerPropertiesChain,
            arg2: *mut u32,
            arg3: *mut VkLayerProperties,
        ) -> VkResult,
    >,
    pub pNextLink: *const VkEnumerateInstanceLayerPropertiesChain,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkEnumerateInstanceLayerPropertiesChain"]
        [::std::mem::size_of::<VkEnumerateInstanceLayerPropertiesChain>() - 32usize];
    ["Alignment of VkEnumerateInstanceLayerPropertiesChain"]
        [::std::mem::align_of::<VkEnumerateInstanceLayerPropertiesChain>() - 8usize];
    ["Offset of field: VkEnumerateInstanceLayerPropertiesChain::header"]
        [::std::mem::offset_of!(VkEnumerateInstanceLayerPropertiesChain, header) - 0usize];
    ["Offset of field: VkEnumerateInstanceLayerPropertiesChain::pfnNextLayer"]
        [::std::mem::offset_of!(VkEnumerateInstanceLayerPropertiesChain, pfnNextLayer) - 16usize];
    ["Offset of field: VkEnumerateInstanceLayerPropertiesChain::pNextLink"]
        [::std::mem::offset_of!(VkEnumerateInstanceLayerPropertiesChain, pNextLink) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VkEnumerateInstanceVersionChain {
    pub header: VkChainHeader,
    pub pfnNextLayer: ::std::option::Option<
        unsafe extern "C" fn(arg1: *const VkEnumerateInstanceVersionChain, arg2: *mut u32) -> VkResult,
    >,
    pub pNextLink: *const VkEnumerateInstanceVersionChain,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkEnumerateInstanceVersionChain"][::std::mem::size_of::<VkEnumerateInstanceVersionChain>() - 32usize];
    ["Alignment of VkEnumerateInstanceVersionChain"]
        [::std::mem::align_of::<VkEnumerateInstanceVersionChain>() - 8usize];
    ["Offset of field: VkEnumerateInstanceVersionChain::header"]
        [::std::mem::offset_of!(VkEnumerateInstanceVersionChain, header) - 0usize];
    ["Offset of field: VkEnumerateInstanceVersionChain::pfnNextLayer"]
        [::std::mem::offset_of!(VkEnumerateInstanceVersionChain, pfnNextLayer) - 16usize];
    ["Offset of field: VkEnumerateInstanceVersionChain::pNextLink"]
        [::std::mem::offset_of!(VkEnumerateInstanceVersionChain, pNextLink) - 24usize];
};
