/* automatically generated by rust-bindgen 0.72.1 */
/* and then manually edited by hand, so DON'T REGENERATE,
but DO EDIT THIS FILE MANUALLY */
use crate::types::*;
use crate::generated::*;

pub const MAX_NUM_UNKNOWN_EXTS: u32 = 250;
pub const CURRENT_LOADER_LAYER_INTERFACE_VERSION: u32 = 2;
pub const MIN_SUPPORTED_LOADER_LAYER_INTERFACE_VERSION: u32 = 1;
pub const VK_CURRENT_CHAIN_VERSION: u32 = 1;
pub type PFN_GetPhysicalDeviceProcAddr =
    unsafe extern "system" fn(instance: VkInstance, pName: *const ::std::os::raw::c_char) -> PFN_vkVoidFunction;
pub const LAYER_NEGOTIATE_UNINTIALIZED: VkNegotiateLayerStructType = 0;
pub const LAYER_NEGOTIATE_INTERFACE_STRUCT: VkNegotiateLayerStructType = 1;
pub type VkNegotiateLayerStructType = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkNegotiateLayerInterface {
    pub sType: VkNegotiateLayerStructType,
    pub pNext: *mut ::std::os::raw::c_void,
    pub loaderLayerInterfaceVersion: u32,
    pub pfnGetInstanceProcAddr: PFN_vkGetInstanceProcAddr,
    pub pfnGetDeviceProcAddr: PFN_vkGetDeviceProcAddr,
    pub pfnGetPhysicalDeviceProcAddr: PFN_GetPhysicalDeviceProcAddr,
}
pub type PFN_vkNegotiateLoaderLayerInterfaceVersion =
    unsafe extern "system" fn(pVersionStruct: *mut VkNegotiateLayerInterface) -> VkResult;
pub type PFN_PhysDevExt = unsafe extern "system" fn(phys_device: VkPhysicalDevice) -> VkResult;
pub const VK_LAYER_LINK_INFO: VkLayerFunction = 0;
pub const VK_LOADER_DATA_CALLBACK: VkLayerFunction = 1;
pub const VK_LOADER_LAYER_CREATE_DEVICE_CALLBACK: VkLayerFunction = 2;
pub const VK_LOADER_FEATURES: VkLayerFunction = 3;
pub type VkLayerFunction = ::std::os::raw::c_int;

#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkLayerInstanceLink {
    pub pNext: *mut VkLayerInstanceLink,
    pub pfnNextGetInstanceProcAddr: Option<PFN_vkGetInstanceProcAddr>,
    pub pfnNextGetPhysicalDeviceProcAddr: Option<PFN_GetPhysicalDeviceProcAddr>,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkLayerDeviceInfo {
    pub device_info: *mut ::std::os::raw::c_void,
    pub pfnNextGetInstanceProcAddr: PFN_vkGetInstanceProcAddr,
}
pub type PFN_vkSetInstanceLoaderData =
    unsafe extern "system" fn(instance: VkInstance, object: *mut ::std::os::raw::c_void) -> VkResult;
pub type PFN_vkSetDeviceLoaderData =
    unsafe extern "system" fn(device: VkDevice, object: *mut ::std::os::raw::c_void) -> VkResult;
pub type PFN_vkLayerCreateDevice = unsafe extern "system" fn(
    instance: VkInstance,
    physicalDevice: VkPhysicalDevice,
    pCreateInfo: *const VkDeviceCreateInfo,
    pAllocator: *const VkAllocationCallbacks,
    pDevice: *mut VkDevice,
    layerGIPA: PFN_vkGetInstanceProcAddr,
    nextGDPA: *mut PFN_vkGetDeviceProcAddr,
) -> VkResult;
pub type PFN_vkLayerDestroyDevice = unsafe extern "system" fn(
    physicalDevice: VkDevice,
    pAllocator: *const VkAllocationCallbacks,
    destroyFunction: PFN_vkDestroyDevice,
);
pub const VK_LOADER_FEATURE_PHYSICAL_DEVICE_SORTING: VkLoaderFeastureFlagBits = 1;
pub type VkLoaderFeastureFlagBits = ::std::os::raw::c_int;
pub use self::VkLoaderFeastureFlagBits as VkLoaderFlagBits;
pub type VkLoaderFeatureFlags = VkFlags;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkLayerInstanceCreateInfo {
    pub sType: VkStructureType,
    pub pNext: *const ::std::os::raw::c_void,
    pub function: VkLayerFunction,
    pub u: VkLayerInstanceCreateInfo__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union VkLayerInstanceCreateInfo__bindgen_ty_1 {
    pub pLayerInfo: *mut VkLayerInstanceLink,
    pub pfnSetInstanceLoaderData: PFN_vkSetInstanceLoaderData,
    pub layerDevice: VkLayerInstanceCreateInfo__bindgen_ty_1__bindgen_ty_1,
    pub loaderFeatures: VkLoaderFeatureFlags,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkLayerInstanceCreateInfo__bindgen_ty_1__bindgen_ty_1 {
    pub pfnLayerCreateDevice: PFN_vkLayerCreateDevice,
    pub pfnLayerDestroyDevice: PFN_vkLayerDestroyDevice,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkLayerDeviceLink_ {
    pub pNext: *mut VkLayerDeviceLink_,
    pub pfnNextGetInstanceProcAddr: Option<PFN_vkGetInstanceProcAddr>,
    pub pfnNextGetDeviceProcAddr: Option<PFN_vkGetDeviceProcAddr>,
}
pub type VkLayerDeviceLink = VkLayerDeviceLink_;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkLayerDeviceCreateInfo {
    pub sType: VkStructureType,
    pub pNext: *const ::std::os::raw::c_void,
    pub function: VkLayerFunction,
    pub u: VkLayerDeviceCreateInfo__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union VkLayerDeviceCreateInfo__bindgen_ty_1 {
    pub pLayerInfo: *mut VkLayerDeviceLink,
    pub pfnSetDeviceLoaderData: Option<PFN_vkSetDeviceLoaderData>,
}
unsafe extern "system" {
    pub fn vkNegotiateLoaderLayerInterfaceVersion(pVersionStruct: *mut VkNegotiateLayerInterface) -> VkResult;
}
pub const VK_CHAIN_TYPE_UNKNOWN: VkChainType = 0;
pub const VK_CHAIN_TYPE_ENUMERATE_INSTANCE_EXTENSION_PROPERTIES: VkChainType = 1;
pub const VK_CHAIN_TYPE_ENUMERATE_INSTANCE_LAYER_PROPERTIES: VkChainType = 2;
pub const VK_CHAIN_TYPE_ENUMERATE_INSTANCE_VERSION: VkChainType = 3;
pub type VkChainType = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkChainHeader {
    pub type_: VkChainType,
    pub version: u32,
    pub size: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkEnumerateInstanceExtensionPropertiesChain {
    pub header: VkChainHeader,
    pub pfnNextLayer: Option<
        unsafe extern "system" fn(
            arg1: *const VkEnumerateInstanceExtensionPropertiesChain,
            arg2: *const ::std::os::raw::c_char,
            arg3: *mut u32,
            arg4: *mut VkExtensionProperties,
        ) -> VkResult,
    >,
    pub pNextLink: *const VkEnumerateInstanceExtensionPropertiesChain,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkEnumerateInstanceLayerPropertiesChain {
    pub header: VkChainHeader,
    pub pfnNextLayer: Option<
        unsafe extern "system" fn(
            arg1: *const VkEnumerateInstanceLayerPropertiesChain,
            arg2: *mut u32,
            arg3: *mut VkLayerProperties,
        ) -> VkResult,
    >,
    pub pNextLink: *const VkEnumerateInstanceLayerPropertiesChain,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkEnumerateInstanceVersionChain {
    pub header: VkChainHeader,
    pub pfnNextLayer:
        Option<unsafe extern "system" fn(arg1: *const VkEnumerateInstanceVersionChain, arg2: *mut u32) -> VkResult>,
    pub pNextLink: *const VkEnumerateInstanceVersionChain,
}
