[package]
name = "pipeline-build-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
shader-bridge = { workspace = true }
pipeline-archive = { workspace = true }
serde_json = "1.0.145"
thiserror = "2.0.17"
anyhow = "1.0.100"
color-print = "0.3.7"