[profile.release.build-override]
opt-level = 3

[profile.release-with-dbginfo]
inherits = "release"
debug = true

[profile.release-with-dbginfo.build-override]
inherits = "release"
debug = true

[target.'cfg(any(unix, windows))']
rustflags = ["-Cprefer-dynamic=yes"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-Zshare-generics=off"]
#linker = "rust-lld.exe"

