[package]
name = "gamelib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
gpu = { workspace = true }
math = { workspace = true, features = ["serde"] }
color = { workspace = true }
utils = { workspace = true }
shadertool = { workspace = true, optional = true }
futures = { version = "0.3", features = ["executor"] }
rfd = "0.16.0"
#slab = "0.4"
winit = "0.30"
slotmap = "1.0.7"
threadbound = "0.1.8"
mlua = { version = "0.11.1", features = ["luau", "async"], optional = true }
log = "0.4.27"
env_logger = "0.11.8"
tracy-client = { version = "0.18.4", default-features = false }
bumpalo = "3.19.0"
thiserror = "2.0.16"
egui = { version = "0.32.1", features = ["persistence"] }
keyboard-types = "0.8.0"
arboard = "3.6.0"
renderdoc = "0.12.1"
sharc = { workspace = true }
ab_glyph = "0.2.31"
anyhow = "1.0.100"
tempfile = "3.27.0"
hgeo = { workspace = true }

notify-debouncer-mini = "0.7.0"
libloading = "0.9.0"
ron = "0.12.0"
serde = { version = "1", features = ["derive", "alloc", "rc"] }
color-print = "0.3.7"
scoped-tls = "1.0.1"
planitia-workspace-hack = { version = "0.1", path = "../../planitia-workspace-hack" }

# gamelib itself, and downstream crates that link to gamelib may depend (directly or indirectly) on the same crate but
# with different enabled features. This leads to gamelib being recompiled unnecessarily because of feature mismatches.
# To avoid that as much as possible, we eagerly specify those dependencies here to ensure that they are compiled with
# a set of features that matches how they are used in downstream crates.
# This needs to be updated when a downstream crate adds a potentially conflicting dependency.

# TODO ideally we'd do that, but it's hard to track conflicting dependencies

#       gamelib -> renderdoc -> float-cmp (default features)
# game -> usvg -> strict-num -> float-cmp (no default features, "std")
#float-cmp = { version = "0.9.0", features = ["std"] }


[target.'cfg(target_os="windows")'.dependencies]
windows = { version = "0.61.3", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_Debug",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_SystemServices",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D12",
    "Win32_UI_Shell_Common",
    #"Win32_Graphics_Gdi",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "System",
    "Foundation",
    #"Graphics_DirectX",
    "Foundation_Numerics",
    #"Win32_Graphics_Direct3D11",
    #"Win32_Graphics_DirectWrite",
    "Win32_Security",
    #"Win32_Graphics_Dwm",
    "Win32_Graphics_DirectComposition"] }

[build-dependencies]
shadertool = { workspace = true }

[features]
hot_reload = ["dep:shadertool"]
lua = ["dep:mlua"]
tracy = ["tracy-client/default"]
